-- 코드를 입력하세요
SELECT DISTINCT(A.CAR_ID)
from CAR_RENTAL_COMPANY_CAR as A
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as B
ON A.CAR_ID = B.CAR_ID
where A.CAR_TYPE='세단'
AND
B.START_DATE LIKE '%-10-%'
order by CAR_ID DESC;